### ISSUE TITLE
Hilfe

### ISSUE THREAD

**Issue by Muvid** [Flauschbaellchen/florensia-base#1]
Ich vermisse dine Seite! Und meine versuche die Seite mir Offline anzusehen haben irgendwie nicht hin gehauen und wie ich die Seite einfach wieder Hosten kann habe ich genauso wenig Ahnung.

Kannst du mir evtl ein Programm nennen mit welchen ich deine Seite so anschauen könnte als wenn Sie noch online wäre?

Lg

Muvid

**Comment by Flauschbaellchen** [comment]
Das Einfachste ist wohl die Installation von XAMPP (www.apachefriends.org).
Dort ist PHP sowie die Datenbank bereits enthalten.
Danach die Datenbank importieren, confg.php anpassen und Apache/Webserver konfigurieren.

Ansonsten bitte ich um spezifische Problemfragen mit entsprechenden Betreff.
(Grund-)Kenntnisse sollten schon vorhanden sein.
