### ISSUE TITLE
Problem with sutch scripts

### ISSUE THREAD

**Issue by Dextan** [Flauschbaellchen/florensia-base#2]
First issue is the mbb board dosnt exist but is a must for startup
second many io errors at the language en

**Comment by Dextan** [comment]
Language file "global" for "en" does not exist or not loadable

**Comment by Flauschbaellchen** [comment]
Forum files added by commit 0536c9d4b774812681edb42863d9de50043f14cf
Do you have a more specific error for the missing global 'en' file? E.g. where (file/line) the error is thrown?

**Comment by Dextan** [comment]
not realy thats an error that me shows  in brower let me quick find where the error is

**Comment by Dextan** [comment]
mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in C:\xampp\htdocs\florensia\init.php on line 73
Language file "global" for "en" does not exist or not loadable

**Comment by Flauschbaellchen** [comment]
The error is likely getting thrown on line 100-102 in `init.php`
Check the `confg.php` for `$cfg['language_abs']` and set this to an absolute path where the script can load all language files.
The path should point to the `language` folder located on the root of this git-repository, e.g. 
`/my/github/repos/florensia-base/language`

If this not helps, check line 12-27 in  `init.php` and edit it to your needs if your server's name is not `localhost`.

**Comment by Dextan** [comment]
ok will test  hope i get the page up if it then works i will host it if you allow and reopen it on new domain

**Comment by Dextan** [comment]
ok nun nommal auf deutsch sorry bei mir ist englisch gewohnheit

**Comment by Dextan** [comment]
also das problem mit der sprache hat sich nicht gelöst

**Comment by Dextan** [comment]
ok ein bug beseitigt folgt der nächste echt heftig nun hab ich die meldung Hacking attempt dazu 
Fatal error: Class 'class_florensia' not found in C:\xampp\htdocs\florensia\init.php on line 82

**Comment by Flauschbaellchen** [comment]
1) Check your `confg.php` file if all paths are valid.
2) `init.php` should not be called directly.
3) I need more information, e.g. which script you are calling, the "traceback" as far as you can follow, file layout, content of `confg.php` etc.

**Comment by Dextan** [comment]
ok  if i want open the site it says 
Fatal error: Class 'class_florensia' not found in C:\xampp\htdocs\florensia\init.php on line 82
if you have skype it will easyer to get the site run

**Comment by Flauschbaellchen** [comment]
It's the same information you already posted in your message earlier.

To make some things clear as stated on the frontpage/README:
- The code is for reference only. I strongly advice against setting it up in a production environment.
- You _will need_ own knowledge of PHP, debugging scripts etc.
  I gladly provide additional data I've forgot to check in or give hints if I have some spare time - but I won't debug any bugs or give support as such.

**Comment by Flauschbaellchen** [comment]
No more activity, closed.
