### ISSUE TITLE
Still mybb problem 

### ISSUE THREAD

**Issue by Dextan** [Flauschbaellchen/florensia-base#3]
MyBB has experienced an internal error and cannot continue.

Error Type:
    MyBB Error (42)
Error Message:
    Your board has not yet been upgraded. Please do so before attempting to browse it. 

the error msg from forum softwar

**Comment by Flauschbaellchen** [comment]
Well, what about doing what's requested?
MyBB doc's about upgrading can be found here: http://docs.mybb.com/1.8/install/upgrade/
